import React from "react";

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-14 text-zinc-100">
      <h1 className="text-4xl font-bold mb-4 text-cyan-400">Terms and Conditions</h1>
      <p className="mb-6 text-lg">
        <b>Last updated:</b> July 2025
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">1. Acceptance of Terms</h2>
      <p className="mb-4">
        By accessing or using the CinemAI website, platform, or related services ("CinemAI", "we", "our", "us"), you agree to these Terms and Conditions ("Terms"). If you do not agree to any part of these Terms, you must not use CinemAI.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">2. Service Description</h2>
      <p className="mb-4">
        CinemAI is a streaming platform dedicated to AI-generated movies and series. Content is either created by artificial intelligence or uploaded by accredited users, creators, and studios who have the right to share such content. Features may include video streaming, user accounts, content uploads, recommendations, community interactions, and more.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">3. User Accounts</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>You must be at least 16 years old (or minimum age required in your country) to create an account.</li>
        <li>You agree to provide true, accurate, and complete information during registration and to keep your account information updated.</li>
        <li>You are responsible for all activity under your account and for maintaining the confidentiality of your login credentials.</li>
        <li>We may suspend, restrict, or terminate your account for violations of these Terms or suspected unlawful activity.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">4. User Conduct</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>You agree to use CinemAI only for lawful purposes and in accordance with these Terms.</li>
        <li>You may not attempt to hack, reverse engineer, disrupt, or overload our systems or services.</li>
        <li>You may not upload or share illegal, abusive, hateful, infringing, or otherwise inappropriate content.</li>
        <li>You may not harass, threaten, or impersonate other users.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">5. Content Ownership and Copyright</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>All content available on CinemAI is either generated by artificial intelligence, licensed from creators, or uploaded by users who declare they have rights to share such content.</li>
        <li>You may not copy, download, redistribute, or use CinemAI content except as permitted by platform features.</li>
        <li>If you believe your copyright or intellectual property has been infringed, please contact us via the information provided on our Contact page.</li>
        <li>By uploading content, you grant CinemAI a worldwide, non-exclusive, royalty-free license to use, display, and distribute that content on our platform and related services.</li>
        <li>You retain all rights to your original content, subject to this license.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">6. Artificial Intelligence Content Disclaimer</h2>
      <p className="mb-4">
        CinemAI hosts AI-generated films, videos, and other media. Such content may not always reflect reality, human values, or factual accuracy, and may contain fictional or synthetic characters, events, or imagery. Viewer discretion is advised.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">7. Payments & Subscriptions</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>Certain CinemAI features may require a paid subscription or one-time payment. Prices and features may change at any time, with reasonable notice.</li>
        <li>By subscribing, you authorize us to charge your payment method for recurring fees until you cancel or your subscription is terminated.</li>
        <li>Refunds and cancellations are governed by our Refund Policy (see Privacy/Help pages for details).</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">8. Privacy and Cookies</h2>
      <p className="mb-4">
        Your privacy is important to us. Please review our <a href="/privacy" className="underline text-cyan-400">Privacy Policy</a> to understand how we collect, use, store, and share your information. By using CinemAI, you consent to the use of cookies and tracking technologies as described in our Privacy Policy.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">9. Moderation and Takedown</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>We reserve the right to remove any content or suspend any account for violating these Terms, legal requirements, or community standards, at our sole discretion.</li>
        <li>We are not liable for content uploaded by users or created by AI; however, we act promptly upon reports of illegal or infringing content.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">10. Disclaimer and Limitation of Liability</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>CinemAI is provided "as is" and "as available" without warranties of any kind, either express or implied.</li>
        <li>We do not guarantee uninterrupted or error-free access to the platform.</li>
        <li>To the fullest extent permitted by law, CinemAI and its team are not liable for indirect, incidental, or consequential damages resulting from use of the platform or its content.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-3 mt-8">11. Changes to These Terms</h2>
      <p className="mb-4">
        CinemAI may update these Terms from time to time. Material changes will be notified via the platform or by email, where possible. Continued use of CinemAI after changes constitutes acceptance of the revised Terms.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">12. Governing Law</h2>
      <p className="mb-4">
        These Terms are governed by the laws of your country of residence, except where local regulations require otherwise. Disputes will be resolved in accordance with applicable law and in good faith.
      </p>

      <h2 className="text-2xl font-bold mb-3 mt-8">13. Contact Information</h2>
      <p className="mb-2">
        For any questions, copyright claims, or legal issues regarding these Terms or CinemAI, please contact us via the details listed on our <a href="/contact" className="underline text-cyan-400">Contact page</a>.
      </p>

      <p className="mt-12 text-xs text-zinc-400">
        By using CinemAI, you acknowledge that you have read, understood, and agree to these Terms and Conditions.
      </p>
    </div>
  );
}
